#!/usr/bin/env bash
# finds ip of a given subdomain
#+ usage: script domain subdomain

subdomain_info (){
    full_domain="$2.$1"
    ip=$(dig "$full_domain" | grep "^$full_domain" | awk '{print $5}')
    record=$(dig "$full_domain" | grep "^$full_domain" | awk '{print $4}')

    echo "The subdomain $2 is a $record record and points to $ip"

    return 0
}

if [[ $2 ]]; then
    subdomain_info "$1" "$2"
else
    subdomain_info "$1" "www"
    subdomain_info "$1" "lb-01"
    subdomain_info "$1" "web-01"
    subdomain_info "$1" "web-02"
fi
