#!/usr/bin/env bash
# installs haproxy, and configures it to balance the load between 2 servers.

apt update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.9
apt-get -y install haproxy=2.9.\*

echo "defaults
  mode http
  timeout client 10s
  timeout connect 5s
  timeout server 10s 
  timeout http-request 10s

frontend myfrontend
  bind 127.0.0.1:80
  default_backend myservers

backend myservers
  server server1 34.203.33.120:80
  server server2 54.167.185.108:80" > /etc/haproxy/haproxy.cfg

service haproxy restart
