#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
#+ Displays To infinity and beyond indefinitely
#+ Displays I hate the kill command when receiving a SIGTERM signal
#+ Displays Y U no love me?! when receiving a SIGINT signal
#+ Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

tostop=0

echo $$ > /var/run/myscript.pid
trap "echo I hate the kill command ; rm /var/run/myscript.pid ; tostop=1" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm /var/run/myscript.pid ; tostop=1" SIGQUIT

while [ $tostop -eq 0 ]
do
    echo "To infinity and beyond"
done
