#!/usr/bin/env bash
# This script is displaying "Best School" 8 times, exclusing 4th and 8th iteration
#+ displays "bad luck" in the 4th iteration
#+ displays "good luck" in the 8th iteration

i=0
while [ $i -lt 10 ]
do
    ((i++))
    if [ "$i" -eq 4 ]; then
    echo "bad luck"
    elif [ "$i" -eq 8 ]; then
    echo "good luck"
    else
    echo "Best School"
    fi
done
