#!/usr/bin/env bash
# installs ufw, deny all incoming traffic except ssh, http and https

apt update
apt upgrade
apt install -y ufw

ufw default deny incoming
ufw allow ssh
ufw allow https
ufw allow http
ufw enable
