#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements:
#+ localhost resolves to 127.0.0.2
#+ facebook.com resolves to 8.8.8.8

HOSTS_PATH="/etc/hosts"
HOSTS_COPY_PATH="$HOME/hosts_copy"

# make a temorary copy of the hosts file
cat "$HOSTS_PATH" > "$HOSTS_COPY_PATH"
# make changes in the temprary copy
sed -i -E 's/127.0.0.1\s+localhost/127.0.0.2\tlocalhost/' "$HOSTS_COPY_PATH"
echo -e "8.8.8.8\tfacebook.com" >> "$HOSTS_COPY_PATH"
# push the copy-s content to the original hosts file
cat "$HOSTS_COPY_PATH" > "$HOSTS_PATH"
# remove the temprary copy
rm "$HOSTS_COPY_PATH"
